---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: fluxcd
  annotations:
    fluxcd.io/automated: "true"
spec:
  helmVersion: v3
  releaseName: fluxcd
  chart:
    git: https://github.com/fluxcd/flux.git
    path: charts/flux
    ref: master
  valuesFrom:
  - configMapKeyRef:
      name: fluxcd-properties
      namespace: fluxcd
      key: values.yaml
      optional: false