---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: fluxcd
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: fluxcd
  chart:
    repository: charts.fluxcd.io
    chart: flux
  valuesFrom:
  - configMapKeyRef:
      name: fluxcd-properties
      namespace: fluxcd
      key: values.yaml
      optional: false