---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    fluxcd.io/automated: "true"
spec:
  helmVersion: v3
  releaseName: ingress-nginx
  chart:
    git: https://github.com/kubernetes/ingress-nginx.git
    path: charts/ingress-nginx
    ref: master
  values:
    installCRDs: true
  valuesFrom:
  - configMapKeyRef:
      name: ingress-nginx-properties
      namespace: ingress-nginx
      key: values.yaml
      optional: true