---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: ingress-nginx
  chart:
    repo: https://kubernetes.github.io/ingress-nginx
    path: ingress-nginx
  values:
    controller:
      replicaCount: 2