apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aad-pod-identity
  namespace: pod-identity
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: aad-pod-identity
  chart:
    git: https://github.com/Azure/aad-pod-identity.git
    path: charts/aad-pod-identity
    ref: master
  # values:
  #   azureIdentities:
  #   - name: "pod-identity"
  #     type: 0
  #     enabled: "true"
  #     resourceID: 
  #       valueFrom:
  #         configMapKeyRef:
  #           name: pod-identity-properties
  #           key: ENV_AZURE_MSI_RESOURCE_ID
  #     clientID:
  #       valueFrom:
  #         configMapKeyRef:
  #           name: pod-identity-properties
  #           key: ENV_AZURE_MSI_CLIENT_ID
  #     binding:
  #       name: "podidentitybinding"
  #       selector: "podidentity"
