---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: csi-secrets
  annotations:
    fluxcd.io/automated: "true"
spec:
  helmVersion: v3
  releaseName: csi-secrets-store
  chart:
    git: https://github.com/Azure/secrets-store-csi-driver-provider-azure.git
    path: charts/csi-secrets-store-provider-azure
    ref: master
  values:
    constructPEMChain: true
    secrets-store-csi-driver:
      syncSecret:
        enabled: true